[package]
name = "byu-cs-686-verus"
version = "0.1.0"
edition = "2024"

[dependencies]
# No dependencies for cargo builds - this is a Verus-only project

[package.metadata.verus]
verify = true

[package.metadata.verus.ide]
extra_args = "--rlimit 100000"
